<?php

$lines = static fn (array $items): string => implode("\n", $items);

return [
    'site' => [
        'site_name' => 'Корпоративный проект',
        'phone_1' => '+7 900 200-00-00',
        'phone_2' => '+7 900 200-00-01',
        'email' => 'team@corporate-demo.ru',
        'address_main' => 'Москва, Пресненская набережная, 12',
        'worktime_main' => 'Пн-Пт с 09:00 до 18:00',
        'social' => ['tg' => '', 'wa' => '', 'vk' => ''],
        'logo' => null,
        'hero_image' => null,
        'team_image' => null,
        'developer_logo' => null,
        'seo_title' => 'Корпоративный проект',
        'seo_description' => 'Профиль корпоративного сайта на базе универсального шаблона.',
        'seo_keywords' => 'корпоративный сайт, b2b, шаблон сайта, laravel, filament, vue',
        'map_lat' => 55.7558,
        'map_lng' => 37.6173,
        'map_zoom' => 16,
        'theme_body_bg' => '#F2F6FA',
        'theme_nav_bg' => '#edf0f0',
        'theme_accent_bg' => '#fefeff',
        'theme_text_body' => '#494949',
        'theme_text_secondary' => '#7a7777',
        'theme_text_accent' => '#DAC5A7',
        'theme_border_color' => '#6c5d48',
    ],
    'blocks' => [
        [
            'key' => 'header',
            'title' => 'Шапка сайта',
            'content' => '',
            'is_enabled' => true,
            'sort_order' => 5,
            'meta' => [
                'section_id' => 'header',
                'booking_label' => 'Запросить консультацию',
                'booking_url' => 'https://example.com/request',
                'department_url' => 'https://example.com/company',
                'logo_title' => 'Корпоративный проект',
                'logo_lines' => "КОРПОРАТИВНЫЙ\nПРОЕКТ",
                'logo_alt' => 'Логотип корпоративного проекта',
            ],
        ],
        [
            'key' => 'hero',
            'title' => 'Корпоративный сайт',
            'content' => 'для B2B-продукта или компании',
            'is_enabled' => true,
            'sort_order' => 10,
            'meta' => ['section_id' => 'hero'],
        ],
        [
            'key' => 'about',
            'title' => 'О компании',
            'content' => 'Профиль запуска для корпоративного сайта, B2B-продукта или компании с длинным циклом сделки.',
            'is_enabled' => true,
            'sort_order' => 20,
            'meta' => [
                'section_id' => 'about',
                'content_alignment' => 'left',
                'block1_title' => 'Что должен давать такой сайт',
                'block1_items' => $lines(['Понятное позиционирование', 'Доверие к команде', 'Прозрачный путь к заявке']),
                'block1_history_title' => 'Зачем использовать профиль',
                'block1_history_text' => 'Корпоративный профиль помогает стартовать не с пустого шаблона, а с уже подходящей логики подачи.',
                'history_text' => $lines([
                    'В шаблоне уже есть секции для компании, предложений, команды, отзывов и контактов.',
                    'Админка позволяет быстро адаптировать структуру под новый бизнес и коммерческий сценарий.',
                ]),
                'block2_title' => 'Какие блоки здесь работают лучше всего',
                'block2_group1_title' => 'Для коммерции',
                'block2_group1_items' => $lines(['Решения и продукты', 'Сценарии внедрения', 'Контактная точка для заявки']),
                'block2_group2_title' => 'Для доверия и бренда',
                'block2_group2_items' => $lines(['Команда', 'Кейсы', 'Отзывы клиентов']),
                'block3_lead' => 'Профиль ориентирован на корпоративную подачу и долгий цикл принятия решения.',
                'block3_diagnosis' => 'Здесь удобно показывать решения, индустриальные сценарии, опыт команды и формат взаимодействия.',
                'block3_text' => 'Контент остается управляемым через админку и не требует ручного редактирования кода для каждой итерации сайта.',
                'block4_title' => 'Что уже включено в основу',
                'block4_items' => $lines(['Laravel backend', 'Filament admin', 'Vue storefront', 'SEO и контакты', 'Отзывы и форма заявки']),
                'final_text' => $lines([
                    'Профиль подходит для быстрого разворота корпоративной посадочной страницы.',
                    'После установки замените demo-контент на материалы компании, офферы и ссылки.',
                ]),
            ],
        ],
        [
            'key' => 'services',
            'title' => 'Решения',
            'content' => 'Основные продукты, сервисные пакеты или направления работы компании. Список редактируется отдельно и отражается на витрине без пересборки.',
            'is_enabled' => true,
            'sort_order' => 30,
            'meta' => [
                'section_id' => 'services',
                'content_alignment' => 'left',
            ],
        ],
        [
            'key' => 'doctors',
            'title' => 'Команда',
            'content' => 'Люди, которые отвечают за продукт, реализацию и сопровождение корпоративных клиентов.',
            'is_enabled' => true,
            'sort_order' => 40,
            'meta' => [
                'section_id' => 'pricing',
                'subtitle' => 'КЛЮЧЕВАЯ КОМАНДА',
                'team_count_label' => 'Команда компании',
                'team_image_alt' => 'Команда компании',
                'content_alignment' => 'center',
                'subtitle_alignment' => 'center',
                'team_heading_alignment' => 'center',
            ],
        ],
        [
            'key' => 'gallery',
            'title' => 'Галерея',
            'content' => '',
            'is_enabled' => true,
            'sort_order' => 50,
            'meta' => [
                'section_id' => 'gallery',
                'prev_label' => '← Назад',
                'next_label' => 'Вперед →',
            ],
        ],
        [
            'key' => 'reviews',
            'title' => 'Отзывы клиентов',
            'content' => '',
            'is_enabled' => true,
            'sort_order' => 60,
            'meta' => [
                'section_id' => 'reviews',
                'doctor_prefix' => 'Эксперт:',
                'prev_label' => '← Назад',
                'next_label' => 'Вперед →',
                'prev_aria_label' => 'Предыдущие отзывы',
                'next_aria_label' => 'Следующие отзывы',
                'form_title' => 'Добавить отзыв',
                'name_label' => 'Ваше имя:',
                'name_placeholder' => 'Введите ваше имя',
                'doctor_label' => 'Выберите эксперта:',
                'doctor_placeholder' => '-- Выберите эксперта --',
                'rating_label' => 'Оценка (1-5):',
                'rating_placeholder' => 'Оцените от 1 до 5',
                'review_text_label' => 'Текст отзыва:',
                'review_text_placeholder' => 'Напишите ваш отзыв',
                'submit_label' => 'Оставить отзыв',
                'submitting_label' => 'Отправка...',
                'success_message' => 'Спасибо! Отзыв принят на модерацию.',
                'error_message' => 'Ошибка при отправке отзыва',
                'network_error_message' => 'Не удалось отправить отзыв.',
                'spam_message' => 'Обнаружена спам-активность.',
                'captcha_missing_message' => 'Капча не настроена. Сообщите администратору сайта.',
                'captcha_required_message' => 'Подтвердите, что вы не робот.',
                'anonymous_label' => 'Аноним',
                'initial_reviews' => json_encode([
                    ['author_name' => 'Алексей', 'doctor_name' => 'Дмитрий Павлов', 'rating' => 5, 'text' => 'Команда быстро собрала понятную структуру сайта и аккуратно подготовила запуск.'],
                    ['author_name' => 'Наталья', 'doctor_name' => 'Елена Крылова', 'rating' => 5, 'text' => 'Хорошо чувствуется B2B-логика: четко, структурно и без лишнего визуального шума.'],
                    ['author_name' => 'Павел', 'doctor_name' => 'Михаил Романов', 'rating' => 4, 'text' => 'Хороший demo-отзыв для корпоративного профиля шаблона.'],
                ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
            ],
        ],
        [
            'key' => 'contact',
            'title' => 'Контакты',
            'content' => '',
            'is_enabled' => true,
            'sort_order' => 70,
            'meta' => ['section_id' => 'contact'],
        ],
        [
            'key' => 'map',
            'title' => 'Офис',
            'content' => 'Москва',
            'is_enabled' => true,
            'sort_order' => 80,
            'meta' => [
                'section_id' => 'map-section',
                'menu_label' => 'Карта',
                'map_aria_label' => 'Карта офиса',
                'fallback_text' => 'Не удалось загрузить карту офиса.',
                'fallback_link_text' => 'Открыть адрес на карте',
            ],
        ],
        [
            'key' => 'footer',
            'title' => 'Корпоративный проект',
            'content' => 'Решения, команда и контактные данные для B2B-сценария.',
            'is_enabled' => true,
            'sort_order' => 90,
            'meta' => [
                'section_id' => 'footer',
                'developer_label' => 'Разработчик',
                'developer_url' => 'https://kavweb.ru',
                'developer_aria_label' => 'Перейти на сайт разработчика',
                'copyright' => '© 2026. Все права защищены.',
            ],
        ],
    ],
    'team' => [
        ['full_name' => 'Дмитрий Павлов', 'position' => 'CEO', 'regalia' => 'Стратегия', 'description' => 'Определяет направление развития продукта и коммерческую модель.'],
        ['full_name' => 'Елена Крылова', 'position' => 'Директор по развитию', 'regalia' => 'B2B', 'description' => 'Отвечает за продажи, партнерства и масштабирование корпоративного направления.'],
        ['full_name' => 'Михаил Романов', 'position' => 'Руководитель delivery', 'regalia' => 'Внедрение', 'description' => 'Собирает проектную команду и отвечает за результат внедрения.'],
        ['full_name' => 'Анна Белова', 'position' => 'Client success lead', 'regalia' => 'Поддержка', 'description' => 'Сопровождает клиентов после запуска и помогает развивать проект дальше.'],
    ],
    'services' => [
        ['title' => 'Аудит текущей воронки', 'group' => 'Консалтинг'],
        ['title' => 'Проектирование корпоративного лендинга', 'group' => 'Запуск'],
        ['title' => 'Подготовка коммерческого контента', 'group' => 'Контент'],
        ['title' => 'Интеграция CRM и форм', 'group' => 'Технические работы'],
        ['title' => 'SEO-структура и аналитика', 'group' => 'Маркетинг'],
        ['title' => 'Сопровождение после запуска', 'group' => 'Поддержка'],
    ],
    'gallery' => [
        ['caption' => 'Командная встреча', 'alt' => 'Командная встреча'],
        ['caption' => 'Презентация решения', 'alt' => 'Презентация решения'],
        ['caption' => 'Работа с клиентским проектом', 'alt' => 'Работа с клиентским проектом'],
    ],
    'reviews' => [
        ['author_name' => 'Алексей', 'doctor_name' => 'Дмитрий Павлов', 'rating' => 5, 'text' => 'Команда быстро собрала понятную структуру сайта и аккуратно подготовила запуск.'],
        ['author_name' => 'Наталья', 'doctor_name' => 'Елена Крылова', 'rating' => 5, 'text' => 'Хорошо чувствуется B2B-логика: четко, структурно и без лишнего визуального шума.'],
        ['author_name' => 'Павел', 'doctor_name' => 'Михаил Романов', 'rating' => 4, 'text' => 'Хороший demo-отзыв для корпоративного профиля шаблона.'],
    ],
];
