<?php

$lines = static fn (array $items): string => implode("\n", $items);

return [
    'site' => [
        'site_name' => 'Медицинский центр',
        'phone_1' => '+7 900 100-00-00',
        'phone_2' => '+7 900 100-00-01',
        'email' => 'info@medical-demo.ru',
        'address_main' => 'Санкт-Петербург, Большой проспект, 10',
        'worktime_main' => 'Ежедневно с 08:00 до 20:00',
        'social' => ['tg' => '', 'wa' => '', 'vk' => ''],
        'logo' => null,
        'hero_image' => null,
        'team_image' => null,
        'developer_logo' => null,
        'seo_title' => 'Медицинский центр',
        'seo_description' => 'Профиль медицинского сайта на базе универсального шаблона.',
        'seo_keywords' => 'медицинский сайт, клиника, шаблон сайта, laravel, filament, vue',
        'map_lat' => 59.9386,
        'map_lng' => 30.3141,
        'map_zoom' => 16,
        'theme_body_bg' => '#F2F6FA',
        'theme_nav_bg' => '#edf0f0',
        'theme_accent_bg' => '#fefeff',
        'theme_text_body' => '#494949',
        'theme_text_secondary' => '#7a7777',
        'theme_text_accent' => '#DAC5A7',
        'theme_border_color' => '#6c5d48',
    ],
    'blocks' => [
        [
            'key' => 'header',
            'title' => 'Шапка сайта',
            'content' => '',
            'is_enabled' => true,
            'sort_order' => 5,
            'meta' => [
                'section_id' => 'header',
                'booking_label' => 'Записаться',
                'booking_url' => 'https://example.com/appointment',
                'department_url' => 'https://example.com/clinic',
                'logo_title' => 'Медицинский центр',
                'logo_lines' => "МЕДИЦИНСКИЙ\nЦЕНТР",
                'logo_alt' => 'Логотип медицинского центра',
            ],
        ],
        [
            'key' => 'hero',
            'title' => 'Забота о пациентах',
            'content' => 'с понятной навигацией и управляемым контентом',
            'is_enabled' => true,
            'sort_order' => 10,
            'meta' => ['section_id' => 'hero'],
        ],
        [
            'key' => 'about',
            'title' => 'О центре',
            'content' => 'Профиль запуска для частной клиники, диагностического отделения или медицинского кабинета.',
            'is_enabled' => true,
            'sort_order' => 20,
            'meta' => [
                'section_id' => 'about',
                'content_alignment' => 'left',
                'block1_title' => 'Что важно пациенту',
                'block1_items' => $lines(['Быстрая запись', 'Прозрачный список услуг', 'Понятные контакты и график работы']),
                'block1_history_title' => 'Что можно упаковать в шаблоне',
                'block1_history_text' => 'Шаблон позволяет быстро собрать медицинский сайт с управляемыми блоками, специалистами, отзывами и SEO-данными.',
                'history_text' => $lines([
                    'Контент врача, список направлений, галерея и отзывы редактируются через админку.',
                    'Базовая структура подходит для клиник, диагностических отделений и частных кабинетов.',
                ]),
                'block2_title' => 'Какие смыслы можно показать',
                'block2_group1_title' => 'Для пациента',
                'block2_group1_items' => $lines(['Специалисты', 'Услуги и диагностика', 'Как записаться']),
                'block2_group2_title' => 'Для доверия',
                'block2_group2_items' => $lines(['Опыт центра', 'Отзывы пациентов', 'Лицензии и контактная информация']),
                'block3_lead' => 'Профиль ориентирован на медицинскую подачу без необходимости переписывать код шаблона.',
                'block3_diagnosis' => 'Можно вынести отделения, направления диагностики, преимущества клиники и логистику записи.',
                'block3_text' => 'Администратор центра меняет тексты, список услуг, отзывы и состав специалистов без участия разработчика.',
                'block4_title' => 'Что уже предусмотрено',
                'block4_items' => $lines(['Секция специалистов', 'Каталог услуг/диагностики', 'Форма отзывов', 'Контакты и карта', 'SEO и админка']),
                'final_text' => $lines([
                    'После установки замените demo-данные на реальные данные центра.',
                    'Медицинский профиль сохраняет общую архитектуру шаблона, но стартует с отраслевого контента.',
                ]),
            ],
        ],
        [
            'key' => 'services',
            'title' => 'Направления',
            'content' => 'Список услуг, диагностических направлений или медицинских программ. Пункты редактируются отдельно и сразу отображаются на витрине.',
            'is_enabled' => true,
            'sort_order' => 30,
            'meta' => [
                'section_id' => 'services',
                'content_alignment' => 'left',
            ],
        ],
        [
            'key' => 'doctors',
            'title' => 'Специалисты',
            'content' => 'Команда врачей и медицинских специалистов, которые работают с пациентами и отвечают за качество сервиса.',
            'is_enabled' => true,
            'sort_order' => 40,
            'meta' => [
                'section_id' => 'pricing',
                'subtitle' => 'СПЕЦИАЛИСТЫ ЦЕНТРА',
                'team_count_label' => 'Сотрудники центра',
                'team_image_alt' => 'Команда специалистов центра',
                'content_alignment' => 'center',
                'subtitle_alignment' => 'center',
                'team_heading_alignment' => 'center',
            ],
        ],
        [
            'key' => 'gallery',
            'title' => 'Галерея',
            'content' => '',
            'is_enabled' => true,
            'sort_order' => 50,
            'meta' => [
                'section_id' => 'gallery',
                'prev_label' => '← Назад',
                'next_label' => 'Вперед →',
            ],
        ],
        [
            'key' => 'reviews',
            'title' => 'Отзывы пациентов',
            'content' => '',
            'is_enabled' => true,
            'sort_order' => 60,
            'meta' => [
                'section_id' => 'reviews',
                'doctor_prefix' => 'Специалист:',
                'prev_label' => '← Назад',
                'next_label' => 'Вперед →',
                'prev_aria_label' => 'Предыдущие отзывы',
                'next_aria_label' => 'Следующие отзывы',
                'form_title' => 'Добавить отзыв',
                'name_label' => 'Ваше имя:',
                'name_placeholder' => 'Введите ваше имя',
                'doctor_label' => 'Выберите специалиста:',
                'doctor_placeholder' => '-- Выберите специалиста --',
                'rating_label' => 'Оценка (1-5):',
                'rating_placeholder' => 'Оцените от 1 до 5',
                'review_text_label' => 'Текст отзыва:',
                'review_text_placeholder' => 'Напишите ваш отзыв',
                'submit_label' => 'Оставить отзыв',
                'submitting_label' => 'Отправка...',
                'success_message' => 'Спасибо! Отзыв принят на модерацию.',
                'error_message' => 'Ошибка при отправке отзыва',
                'network_error_message' => 'Не удалось отправить отзыв.',
                'spam_message' => 'Обнаружена спам-активность.',
                'captcha_missing_message' => 'Капча не настроена. Сообщите администратору сайта.',
                'captcha_required_message' => 'Подтвердите, что вы не робот.',
                'anonymous_label' => 'Аноним',
                'initial_reviews' => json_encode([
                    ['author_name' => 'Ольга', 'doctor_name' => 'Екатерина Власова', 'rating' => 5, 'text' => 'Удобная запись, спокойная атмосфера и понятные рекомендации после приема.'],
                    ['author_name' => 'Сергей', 'doctor_name' => 'Андрей Морозов', 'rating' => 5, 'text' => 'Все организовано быстро и без лишней суеты, результаты объяснили доступно.'],
                    ['author_name' => 'Анна', 'doctor_name' => 'Наталья Орлова', 'rating' => 4, 'text' => 'Хороший demo-отзыв для медицинского профиля шаблона.'],
                ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
            ],
        ],
        [
            'key' => 'contact',
            'title' => 'Контакты',
            'content' => '',
            'is_enabled' => true,
            'sort_order' => 70,
            'meta' => ['section_id' => 'contact'],
        ],
        [
            'key' => 'map',
            'title' => 'Как добраться',
            'content' => 'Санкт-Петербург',
            'is_enabled' => true,
            'sort_order' => 80,
            'meta' => [
                'section_id' => 'map-section',
                'menu_label' => 'Карта',
                'map_aria_label' => 'Карта проезда к медицинскому центру',
                'fallback_text' => 'Не удалось загрузить карту центра.',
                'fallback_link_text' => 'Открыть адрес на карте',
            ],
        ],
        [
            'key' => 'footer',
            'title' => 'Медицинский центр',
            'content' => 'Информация о центре, ключевых услугах и способах записи.',
            'is_enabled' => true,
            'sort_order' => 90,
            'meta' => [
                'section_id' => 'footer',
                'developer_label' => 'Разработчик',
                'developer_url' => 'https://kavweb.ru',
                'developer_aria_label' => 'Перейти на сайт разработчика',
                'copyright' => '© 2026. Все права защищены.',
            ],
        ],
    ],
    'team' => [
        ['full_name' => 'Екатерина Власова', 'position' => 'Главный врач', 'regalia' => 'Терапия', 'description' => 'Курирует медицинское направление, качество сервиса и коммуникацию с пациентами.'],
        ['full_name' => 'Андрей Морозов', 'position' => 'Врач диагностики', 'regalia' => 'УЗИ', 'description' => 'Отвечает за диагностические исследования и маршрут пациента внутри центра.'],
        ['full_name' => 'Наталья Орлова', 'position' => 'Кардиолог', 'regalia' => 'Консультации', 'description' => 'Проводит консультации и помогает выстраивать индивидуальные рекомендации.'],
        ['full_name' => 'Марина Федорова', 'position' => 'Координатор записи', 'regalia' => 'Сервис', 'description' => 'Сопровождает пациентов по записи, документам и организационным вопросам.'],
    ],
    'services' => [
        ['title' => 'Первичная консультация', 'group' => 'Прием'],
        ['title' => 'Повторный прием', 'group' => 'Прием'],
        ['title' => 'Ультразвуковая диагностика', 'group' => 'Диагностика'],
        ['title' => 'Функциональные исследования', 'group' => 'Диагностика'],
        ['title' => 'Check-up программа', 'group' => 'Программы'],
        ['title' => 'Сопровождение пациента', 'group' => 'Сервис'],
    ],
    'gallery' => [
        ['caption' => 'Зона приема пациентов', 'alt' => 'Зона приема пациентов'],
        ['caption' => 'Кабинет консультаций', 'alt' => 'Кабинет консультаций'],
        ['caption' => 'Диагностическое оборудование', 'alt' => 'Диагностическое оборудование'],
    ],
    'reviews' => [
        ['author_name' => 'Ольга', 'doctor_name' => 'Екатерина Власова', 'rating' => 5, 'text' => 'Удобная запись, спокойная атмосфера и понятные рекомендации после приема.'],
        ['author_name' => 'Сергей', 'doctor_name' => 'Андрей Морозов', 'rating' => 5, 'text' => 'Все организовано быстро и без лишней суеты, результаты объяснили доступно.'],
        ['author_name' => 'Анна', 'doctor_name' => 'Наталья Орлова', 'rating' => 4, 'text' => 'Хороший demo-отзыв для медицинского профиля шаблона.'],
    ],
];
