<?php

$lines = static fn (array $items): string => implode("\n", $items);

return [
    'site' => [
        'site_name' => 'Экспертный сервис',
        'phone_1' => '+7 900 000-00-00',
        'phone_2' => '+7 900 000-00-01',
        'email' => 'hello@service-demo.ru',
        'address_main' => 'Санкт-Петербург, Невский проспект, 1',
        'worktime_main' => 'Пн-Пт с 10:00 до 19:00',
        'social' => ['tg' => '', 'wa' => '', 'vk' => ''],
        'logo' => null,
        'hero_image' => null,
        'team_image' => null,
        'developer_logo' => null,
        'seo_title' => 'Экспертный сервис',
        'seo_description' => 'Шаблон сервисного лендинга на Laravel, Filament и Vue 3.',
        'seo_keywords' => 'сервисный лендинг, шаблон сайта, laravel, filament, vue',
        'map_lat' => 59.9386,
        'map_lng' => 30.3141,
        'map_zoom' => 16,
        'theme_body_bg' => '#F2F6FA',
        'theme_nav_bg' => '#edf0f0',
        'theme_accent_bg' => '#fefeff',
        'theme_text_body' => '#494949',
        'theme_text_secondary' => '#7a7777',
        'theme_text_accent' => '#DAC5A7',
        'theme_border_color' => '#6c5d48',
    ],
    'blocks' => [
        [
            'key' => 'header',
            'title' => 'Шапка сайта',
            'content' => '',
            'is_enabled' => true,
            'sort_order' => 5,
            'meta' => [
                'section_id' => 'header',
                'booking_label' => 'Связаться',
                'booking_url' => 'https://example.com/contact',
                'department_url' => 'https://example.com/about',
                'logo_title' => 'Экспертный сервис',
                'logo_lines' => "ЭКСПЕРТНЫЙ\nСЕРВИС",
                'logo_alt' => 'Логотип сервиса',
            ],
        ],
        [
            'key' => 'hero',
            'title' => 'Современный сервис',
            'content' => 'с управляемым контентом',
            'is_enabled' => true,
            'sort_order' => 10,
            'meta' => ['section_id' => 'hero'],
        ],
        [
            'key' => 'about',
            'title' => 'О проекте',
            'content' => 'Гибкий шаблон для запуска экспертного сервиса, продуктового лендинга или сайта под услуги.',
            'is_enabled' => true,
            'sort_order' => 20,
            'meta' => [
                'section_id' => 'about',
                'content_alignment' => 'left',
                'block1_title' => 'Почему это удобно',
                'block1_items' => $lines(['Управляемый контент', 'Быстрый запуск', 'Чистая структура проекта']),
                'block1_history_title' => 'Как использовать шаблон',
                'block1_history_text' => 'Шаблон закрывает типовую структуру сервисного сайта и не требует ручной правки кода под каждый абзац.',
                'history_text' => $lines([
                    'Все ключевые тексты, списки и подписи управляются через админку.',
                    'Frontend получает данные по API и обновляется без переписывания секций.',
                ]),
                'block2_title' => 'Что можно показать в этом блоке',
                'block2_group1_title' => 'Для клиента',
                'block2_group1_items' => $lines(['Преимущества сервиса', 'Форматы работы', 'Этапы запуска']),
                'block2_group2_title' => 'Для доверия и SEO',
                'block2_group2_items' => $lines(['Опыт команды', 'Кейсы', 'Понятная структура посадочной страницы']),
                'block3_lead' => 'Секция легко адаптируется под любой сервисный сценарий.',
                'block3_diagnosis' => 'Здесь можно рассказать о продукте, логике работы, результате для клиента и процессе сопровождения.',
                'block3_text' => 'Структура специально разложена на редактируемые поля, чтобы контентом управлял администратор, а не разработчик.',
                'block4_title' => 'Что входит в шаблон',
                'block4_items' => $lines(['Laravel backend', 'Filament admin', 'Vue storefront', 'Отзывы с модерацией', 'SEO-базис и адаптив']),
                'final_text' => $lines([
                    'Этот стартовый набор подходит для быстрой сборки нового клиентского проекта.',
                    'После запуска замените demo-контент на реальные материалы и контактные данные.',
                ]),
            ],
        ],
        [
            'key' => 'services',
            'title' => 'Предложения',
            'content' => 'Основные предложения, форматы работы или элементы каталога. Список редактируется отдельно и отображается без пересборки витрины.',
            'is_enabled' => true,
            'sort_order' => 30,
            'meta' => [
                'section_id' => 'services',
                'content_alignment' => 'left',
            ],
        ],
        [
            'key' => 'doctors',
            'title' => 'Команда',
            'content' => 'Люди, которые формируют продукт, сопровождают клиентов и отвечают за результат.',
            'is_enabled' => true,
            'sort_order' => 40,
            'meta' => [
                'section_id' => 'pricing',
                'subtitle' => 'КЛЮЧЕВЫЕ УЧАСТНИКИ',
                'team_count_label' => 'Команда проекта',
                'team_image_alt' => 'Команда проекта',
                'content_alignment' => 'center',
                'subtitle_alignment' => 'center',
                'team_heading_alignment' => 'center',
            ],
        ],
        [
            'key' => 'gallery',
            'title' => 'Галерея',
            'content' => '',
            'is_enabled' => true,
            'sort_order' => 50,
            'meta' => [
                'section_id' => 'gallery',
                'prev_label' => '← Назад',
                'next_label' => 'Вперед →',
            ],
        ],
        [
            'key' => 'reviews',
            'title' => 'Отзывы',
            'content' => '',
            'is_enabled' => true,
            'sort_order' => 60,
            'meta' => [
                'section_id' => 'reviews',
                'doctor_prefix' => 'Участник:',
                'prev_label' => '← Назад',
                'next_label' => 'Вперед →',
                'prev_aria_label' => 'Предыдущие отзывы',
                'next_aria_label' => 'Следующие отзывы',
                'form_title' => 'Добавить отзыв',
                'name_label' => 'Ваше имя:',
                'name_placeholder' => 'Введите ваше имя',
                'doctor_label' => 'Выберите участника:',
                'doctor_placeholder' => '-- Выберите участника --',
                'rating_label' => 'Оценка (1-5):',
                'rating_placeholder' => 'Оцените от 1 до 5',
                'review_text_label' => 'Текст отзыва:',
                'review_text_placeholder' => 'Напишите ваш отзыв',
                'submit_label' => 'Оставить отзыв',
                'submitting_label' => 'Отправка...',
                'success_message' => 'Спасибо! Отзыв принят на модерацию.',
                'error_message' => 'Ошибка при отправке отзыва',
                'network_error_message' => 'Не удалось отправить отзыв.',
                'spam_message' => 'Обнаружена спам-активность.',
                'captcha_missing_message' => 'Капча не настроена. Сообщите администратору сайта.',
                'captcha_required_message' => 'Подтвердите, что вы не робот.',
                'anonymous_label' => 'Аноним',
                'initial_reviews' => json_encode([
                    ['author_name' => 'Елена', 'doctor_name' => 'Анна Смирнова', 'rating' => 5, 'text' => 'Понравилась четкая организация, понятная коммуникация и быстрый старт проекта.'],
                    ['author_name' => 'Игорь', 'doctor_name' => 'Иван Петров', 'rating' => 5, 'text' => 'Удобная структура, прозрачный процесс и аккуратная реализация без лишних шагов.'],
                    ['author_name' => 'Марина', 'doctor_name' => 'Мария Волкова', 'rating' => 4, 'text' => 'Хороший demo-отзыв для стартового наполнения сервисного шаблона.'],
                ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
            ],
        ],
        [
            'key' => 'contact',
            'title' => 'Контакты',
            'content' => '',
            'is_enabled' => true,
            'sort_order' => 70,
            'meta' => ['section_id' => 'contact'],
        ],
        [
            'key' => 'map',
            'title' => 'Как нас найти',
            'content' => 'Санкт-Петербург',
            'is_enabled' => true,
            'sort_order' => 80,
            'meta' => [
                'section_id' => 'map-section',
                'menu_label' => 'Карта',
                'map_aria_label' => 'Карта проезда',
                'fallback_text' => 'Не удалось загрузить интерактивную карту.',
                'fallback_link_text' => 'Открыть адрес на карте',
            ],
        ],
        [
            'key' => 'footer',
            'title' => 'Экспертный сервис',
            'content' => 'Сервис, кейсы и контактная информация для нового клиента.',
            'is_enabled' => true,
            'sort_order' => 90,
            'meta' => [
                'section_id' => 'footer',
                'developer_label' => 'Разработчик',
                'developer_url' => 'https://kavweb.ru',
                'developer_aria_label' => 'Перейти на сайт разработчика',
                'copyright' => '© 2026. Все права защищены.',
            ],
        ],
    ],
    'team' => [
        ['full_name' => 'Анна Смирнова', 'position' => 'Руководитель проекта', 'regalia' => 'Стратегия', 'description' => 'Отвечает за структуру продукта, приоритеты и итоговый результат.'],
        ['full_name' => 'Иван Петров', 'position' => 'Продуктовый эксперт', 'regalia' => 'Запуск', 'description' => 'Настраивает логику предложения, оффер и клиентский сценарий.'],
        ['full_name' => 'Мария Волкова', 'position' => 'Менеджер по работе с клиентами', 'regalia' => 'Коммуникация', 'description' => 'Координирует запуск, обратную связь и текущее сопровождение.'],
        ['full_name' => 'Ольга Соколова', 'position' => 'Аналитик', 'regalia' => 'Исследования', 'description' => 'Собирает вводные, помогает с позиционированием и упаковкой контента.'],
    ],
    'services' => [
        ['title' => 'Стратегическая сессия', 'group' => 'Консультации'],
        ['title' => 'Аудит проекта', 'group' => 'Консультации'],
        ['title' => 'Запуск лендинга', 'group' => 'Запуск'],
        ['title' => 'Контент-поддержка', 'group' => 'Поддержка'],
        ['title' => 'SEO-базис', 'group' => 'Поддержка'],
        ['title' => 'Интеграция форм и заявок', 'group' => 'Технические работы'],
    ],
    'gallery' => [
        ['caption' => 'Рабочий процесс команды', 'alt' => 'Рабочий процесс команды'],
        ['caption' => 'Интерфейс проекта', 'alt' => 'Интерфейс проекта'],
        ['caption' => 'Презентация сервиса', 'alt' => 'Презентация сервиса'],
    ],
    'reviews' => [
        ['author_name' => 'Елена', 'doctor_name' => 'Анна Смирнова', 'rating' => 5, 'text' => 'Понравилась четкая организация, понятная коммуникация и быстрый старт проекта.'],
        ['author_name' => 'Игорь', 'doctor_name' => 'Иван Петров', 'rating' => 5, 'text' => 'Удобная структура, прозрачный процесс и аккуратная реализация без лишних шагов.'],
        ['author_name' => 'Марина', 'doctor_name' => 'Мария Волкова', 'rating' => 4, 'text' => 'Хороший demo-отзыв для стартового наполнения сервисного шаблона.'],
    ],
];
